'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SiteMaster

    '''<summary>
    '''bdyProgramMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bdyProgramMaster As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgbtnTRACeLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnTRACeLog As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblUserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RetrievePhotoUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RetrievePhotoUpload As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''UserPhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserPhoto As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lnkbtnMyProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnMyProfile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnLogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnLogout As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnHomePages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnHomePages As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divAssignmentsMain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAssignmentsMain As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''Assignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Assignments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnAssignmentDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAssignmentDashboard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnComplianceAsgtask control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnComplianceAsgtask As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnScheduleAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnScheduleAssignments As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnITReturnsFiling control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnITReturnsFiling As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnDynamicReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnDynamicReports As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnInvoice As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divFOA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFOA As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''financialaudit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents financialaudit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnknavSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnknavSchedule As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fmaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fmaster As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSchedule As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnScheduleDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnScheduleDashboard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnScheduleUploadTrailbalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnScheduleUploadTrailbalance As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnUploadStockEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnUploadStockEntry As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnSchedulenote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSchedulenote As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnScheduleReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnScheduleReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnJournalEntry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnJournalEntry As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divFA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divFA As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''fixedasset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fixedasset As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkNavFixedAsset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNavFixedAsset As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''mastersettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mastersettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnLocationSetUp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnLocationSetUp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnAssetRegister control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAssetRegister As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''assettransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents assettransaction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnAssetAdditionDashBoard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAssetAdditionDashBoard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnAssetDeletionDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAssetDeletionDashboard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnDepreciationComputation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnDepreciationComputation As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''freports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents freports As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnFXAPhysicalReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnFXAPhysicalReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnFXADynamicReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnFXADynamicReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnFXAInvReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnFXAInvReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkConsolidatedReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkConsolidatedReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divStandAudit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStandAudit As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''StandAudit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StandAudit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnAnnualPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAnnualPlan As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnSADashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSADashboard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnSAScheduleAudit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnSAScheduleAudit As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtSamplings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtSamplings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnTrialBalanceReview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnTrialBalanceReview As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnCA As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnAuditSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAuditSummary As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnDigitalfillingRptGen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnDigitalfillingRptGen As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnFinalAuditReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnFinalAuditReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divDigitalOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDigitalOffice As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''divMasters control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMasters As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''master control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents master As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnknavTrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnknavTrace As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''divtrace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divtrace As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnGRACeSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnGRACeSettings As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnOrganizationStructure control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnOrganizationStructure As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnHolidayMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnHolidayMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnCompanyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnCompanyDetails As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnEmployeeMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnEmployeeMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnCustomerMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnCustomerMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnUserMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnUserMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnknavSuperMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnknavSuperMaster As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''supermaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents supermaster As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnGeneralMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnGeneralMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnExcelUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnExcelUpload As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnAssignmentMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAssignmentMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnAuditChecklist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAuditChecklist As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnLogReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnLogReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnknavRptTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnknavRptTemp As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''ReportTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportTemplate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnReportContentMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnReportContentMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnReportTemplateMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnReportTemplateMaster As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder

    '''<summary>
    '''lblValidationMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblValidationMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''logoutmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logoutmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnlogout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnlogout As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lblTimeOutWarning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeOutWarning As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCheckPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCheckPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCheckPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCheckPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCheckPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCheckPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CVCheckPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CVCheckPassword As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''btnCheckPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckPwd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCheckCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheckCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblUPError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUPError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ImagePhoto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImagePhoto As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''lblHeadingLoginName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeadingLoginName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtLoginName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLoginName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSAPcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAPcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSAPcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAPcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmpName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEmpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmpName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesignation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRole As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRole As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPermission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPermission As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPermission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPermission As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMobileNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMobNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMobNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVMobNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMobNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlExperience control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExperience As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSQues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSQues As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVSecurityQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVSecurityQuestion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVSecurityQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVSecurityQuestion As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtSecurityQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSecurityQuestion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAnswer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVAnswer As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVAnswer As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnswer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExperiencesummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExperiencesummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REVExperiencesummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVExperiencesummary As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtExperiencesummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExperiencesummary As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQualification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cblQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblQualification As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''lblOtherQualification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOtherQualification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REVOthers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVOthers As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtOthers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOthers As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnUpdateUserProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpdateUserProfile As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblCPError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrentPasssword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentPasssword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCurrentPasssword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCurrentPasssword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtCurrentPasssword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentPasssword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CVCurrentPasssword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CVCurrentPasssword As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lblNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNewPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVNewPasssword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVNewPasssword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNewPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RegExpNewPwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RegExpNewPwd As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConfirmPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVConfirmPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CVConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CVConfirmPassword As Global.System.Web.UI.WebControls.CompareValidator

    '''<summary>
    '''lblCPNoteHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCPNoteHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCONote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCONote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnCPUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCPUpdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCPCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCPCancel As Global.System.Web.UI.WebControls.Button
End Class
