'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompanyDetails

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divAssignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAssignment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''divAssignmentheader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAssignmentheader As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblpendingtaskcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpendingtaskcount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgbtnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnAdd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbtnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnSave As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbtnUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnUpdate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbtnAddBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnAddBranch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbtnSaveUpdateBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnSaveUpdateBranch As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbtnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnReport As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lnkbtnPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnPDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnExcel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liCompanyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liCompanyDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnCompanyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnCompanyDetails As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liBranchDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liBranchDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnBranchDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnBranchDetails As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divCompanyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompanyDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblHExistingCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHExistingCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlExistingCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExistingCompanyName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyName As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyCode As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyEmail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyContactNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyContactNo1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyContactNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyContactNo1 As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyContactNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyContactNo1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyContactNo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyContactNo1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEstablishmentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEstablishmentDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVEstablishmentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVEstablishmentDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtEstablishmentDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEstablishmentDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cclFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cclFromDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lblWebSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebSite As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWebSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWebSite As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyContactNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyContactNo2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REVCompanyContactNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyContactNo2 As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyContactNo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyContactNo2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyAddress As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyCity As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyCity As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyCountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCountry As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCountry As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVContactPerson As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVContactPerson As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactPerson As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMoblieNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMoblieNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVMoblieNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVMoblieNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVMoblieNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMoblieNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtMoblieNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMoblieNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVState As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVState As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCompanyPinCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCompanyPinCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVCompanyPinCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVCompanyPinCode As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVCompanyPinCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVCompanyPinCode As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCompanyPinCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompanyPinCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblContactMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblContactMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVContactMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVContactMail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVContactMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVContactMail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtContactMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContactMail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblTelephoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTelephoneNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''REVTelephoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVTelephoneNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtTelephoneNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelephoneNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountHolderName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountHolderName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBankName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranch As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConditions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConditions As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Label6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPaymentterms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaymentterms As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''pnlsignature control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlsignature As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''myLogoComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents myLogoComp As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''CompanyLogoUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyLogoUpload As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''divBranchDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divBranchDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RFVExistingCompanyBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVExistingCompanyBranch As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlExistingCompanyBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExistingCompanyBranch As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''REVBranchContactMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVBranchContactMobileNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtBranchContactMobileNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchContactMobileNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVBranchContactLandLineNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVBranchContactLandLineNo As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtBranchContactLandLineNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchContactLandLineNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVBranchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVBranchName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtBranchName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBranchDesignation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchDesignation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVBranchContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVBranchContactEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtBranchContactEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchContactEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVBranchAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVBranchAddress As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtBranchAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchAddress As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVBranchContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVBranchContactPerson As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtBranchContactPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBranchContactPerson As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstboxBranch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstboxBranch As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''ReportViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer
End Class
