'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AuditSummary

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divComp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''imgbtnSaveIFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnSaveIFC As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''imgbtnReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnReport As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lnkbtnPDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnPDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkbtnExcel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnExcel As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblHCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHCustomerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomerName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblHAuditNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHAuditNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAuditNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAuditNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RFVAuditNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVAuditNo As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblHFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHFY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFinancialYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFinancialYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''liAuditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liAuditDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnAuditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnAuditDetails As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liIFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liIFC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnIFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnIFC As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liKAM As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnKAM As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''liMR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents liMR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkbtnMR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnMR As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divAuditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAuditDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkAuditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAuditDetails As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvDashboard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDashboard As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lnkDRL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDRL As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvDRLSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDRLSummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lnkObservationQuerySummarys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkObservationQuerySummarys As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvObservationsQuerySummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvObservationsQuerySummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lnkCheckpointSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkCheckpointSummary As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvCheckpointSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvCheckpointSummary As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divIFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divIFC As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RFVIFCReportDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCReportDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVIFCReportDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVIFCReportDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''cclExpectedCompletionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cclExpectedCompletionDate As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtIFCReportDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCReportDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVIFCReportBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCReportBy As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVIFCReportBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVIFCReportBy As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtIFCReportBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCReportBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSelectFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectFile As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''FUIFCLoad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FUIFCLoad As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''txtIFCPath control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCPath As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOk As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblSheetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSheetName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlIFCSheetName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIFCSheetName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RFVIFCComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCComments As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVIFCComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVIFCComments As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtIFCComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCComments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblHIFCExcelColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHIFCExcelColumns As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lstIFCExcelColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstIFCExcelColumns As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnOkIFCExcelColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnOkIFCExcelColumns As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnConfirmIFCExcelColumns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmIFCExcelColumns As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblIFCNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIFCNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgExcelIFC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgExcelIFC As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dgExcelIFCDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgExcelIFCDetails As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divKAM As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dgKAMdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgKAMdetails As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divMR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMR As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btnNewMRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNewMRR As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dgMRdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgMRdetails As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblIFCHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIFCHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIFCDateOfTesting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCDateOfTesting As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVIFCDateOfTesting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCDateOfTesting As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVIFCDateOfTesting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVIFCDateOfTesting As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CalendarExtender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender1 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''txtIFCSampleSizeUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCSampleSizeUsed As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVIFCSampleSizeUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCSampleSizeUsed As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVIFCSampleSizeUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVIFCSampleSizeUsed As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblIFCConclusion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIFCConclusion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlIFCConclusion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIFCConclusion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RFVIFCConclusion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCConclusion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtIFCTestingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIFCTestingDetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVIFCTestingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVIFCTestingDetails As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVIFCTestingDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVIFCTestingDetails As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnSaveIFCObservationsComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveIFCObservationsComments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblKAMHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKAMHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHKAM As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblKAMDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblKAMDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescriptionOrReasonForSelectionAsKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescriptionOrReasonForSelectionAsKAM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVDescriptionOrReasonForSelectionAsKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVDescriptionOrReasonForSelectionAsKAM As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVDescriptionOrReasonForSelectionAsKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVDescriptionOrReasonForSelectionAsKAM As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtAuditProcedureUndertakenToAddressTheKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAuditProcedureUndertakenToAddressTheKAM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVAuditProcedureUndertakenToAddressTheKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVAuditProcedureUndertakenToAddressTheKAM As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVAuditProcedureUndertakenToAddressTheKAM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVAuditProcedureUndertakenToAddressTheKAM As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnSaveKAMObservationsComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveKAMObservationsComments As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblAuditSummaryValidationMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuditSummaryValidationMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnModalOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalOk As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrowse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnAddAttch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAttch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDesc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dgMainAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgMainAttach As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lblHMRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHManagementRepresentations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHManagementRepresentations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlManagementRepresentations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlManagementRepresentations As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RFVManagementRepresentations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVManagementRepresentations As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''chkSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSendMail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblHMRRHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRequestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRequestedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRequestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRequestedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRequestedByPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRequestedByPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRequestedByPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRequestedByPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHEmailID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RFVEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVEmail As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''REVEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtMRDueDateReceiveDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMRDueDateReceiveDocs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVMRDueDateReceiveDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVMRDueDateReceiveDocs As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVMRDueDateReceiveDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMRDueDateReceiveDocs As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CalendarExtender2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender2 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lblHResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHResponsesReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsesReceivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVResponsesReceivedDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RFEResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFEResponsesReceivedDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''lblHMRRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRRemarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMRRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMRRRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVMRRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVMRRRemarks As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVMRRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVMRRRemarks As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblHResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHResponsesDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsesDetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVResponsesDetails As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVResponsesDetails As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblHResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHResponsesRemarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsesRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVResponsesRemarks As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVResponsesRemarks As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''btnSaveMRRequest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveMRRequest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSaveMRResponses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveMRResponses As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ReportViewer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportViewer1 As Global.Microsoft.Reporting.WebForms.ReportViewer
End Class
