'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MRIssue

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomerName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblHFY control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHFY As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlFinancialYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlFinancialYear As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTaskCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTaskCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlAuditNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAuditNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblHAuditType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHAuditType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAuditType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuditType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgMRdetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgMRdetails As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblHMRR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHManagementRepresentations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHManagementRepresentations As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlManagementRepresentations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlManagementRepresentations As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''RFVManagementRepresentations control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVManagementRepresentations As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lblHMRRHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRHeading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRHeading As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRequestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRequestedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRequestedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRequestedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRequestedByPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRequestedByPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRequestedByPerson control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRequestedByPerson As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRDueDateReceiveDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRDueDateReceiveDocs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRDueDateReceiveDocs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRDueDateReceiveDocs As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHEmailID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEmailID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmailID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHMRRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHMRRRemarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMRRRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMRRRemarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblHResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHResponsesDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsesDetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVResponsesDetails As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVResponsesDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVResponsesDetails As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblHResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHResponsesRemarks As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsesRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVResponsesRemarks As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''REVResponsesRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REVResponsesRemarks As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lblHResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHResponsesReceivedDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsesReceivedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RFVResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFVResponsesReceivedDate As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''RFEResponsesReceivedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFEResponsesReceivedDate As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''CalendarExtender3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CalendarExtender3 As Global.AjaxControlToolkit.CalendarExtender

    '''<summary>
    '''btnSaveMRResponses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveMRResponses As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblBrowse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBrowse As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtfile As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnAddAttch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAttch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblHDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAddDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDesc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dgMainAttach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgMainAttach As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''lblAuditSummaryValidationMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAuditSummaryValidationMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnModalOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnModalOk As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
